#+title: Test page: pointerevent log
#+date: <2023-01-04>
#+nocomments: t

This diagram has a <text> and <circle> inside a <g>, and the <g> has an event logger. The reason I have nested elements is that you can see how pointerover/pointerout differs from pointerenter/pointerleave.

#+begin_export html
<figure class="w-full">
  <svg viewBox="-330 -32 660 64">
    <rect x="-330" y="-32" width="100%" height="100%" fill="url(#pattern-dots)" />
    <g>
      <circle fill="red" stroke="black" stroke-width="0.5" r="30" />
      <text font-size="16" text-anchor="middle" dy="0.4em" fill="white">Test</text>
    </g>
  </svg>
  <figcaption>Logging pointerevents other than move</figcaption>
  <button onclick="clearPre()">Clear log</button>
  <pre class="w-full" id="log"/>
</figure>
#+end_export

The second test shows the event data: (pointer type can be =mouse=, =pen=, =touch= ; pressure can be 0 to around 4)

#+begin_export html
<figure class="w-full">
  <div style="display:grid; grid-template-columns: 100px 1fr 1fr">
    <div id="testbox" style="width:100px;height:100px;background:cyan;user-select:none">TEST</div>
    <pre id="pointerdata"/>
    <div>
      <pre id="forcedata"/>
      <pre id="touchdata"/>
    </div>
  </div>
</figure>
#+end_export

Using =preventDefault()= on a pointer event should cancel the corresponding mouse event or touch event.

https://developer.mozilla.org/en-US/docs/Web/API/Force_Touch_events seems to be active on my mac laptop (touchpad is force sensitive) but /not/ on my phone

On iPhone I don't get a TouchEvent.force or PointerEvent.pressure. On Android I do get that value in both Chrome and Firefox.

Related: https://patrickhlauke.github.io/touch/ and https://patrickhlauke.github.io/getting-touchy-presentation/ (lists touch event order, talks about gestures, which events you can override, hybrid touch events with mouse, lots more)

#+begin_export html
<style>
  svg { background: #eee; box-shadow: 0 1px 3px 1px rgba(0,0,0,0.3); user-select: none; }
  pre { width: unset; max-width: 100%; }
</style>

<x:footer>
  <svg width="0" height="0">
    <defs>
      <pattern id="pattern-dots" width="10" height="10" patternUnits="userSpaceOnUse">
        <circle cx="5" cy="5" fill="hsl(0 10% 80%)" r="1" />
      </pattern>
    </defs>
  </svg>
  <script src="eventlog.js"></script>
</x:footer>
#+end_export
