#+title: Draggable objects, different types
#+date: <2023-01-04>
#+nocomments: t

#+begin_aside
On the main page I test different event handlers. On this page I test dragging /different kinds of things/.
#+end_aside

Things to try with a mouse:

- Drag outside the diagram, and come back {should still be dragging}
- Drag outside the diagram, and let go of the mouse button, then come back into the diagram {should stop dragging}
- Drag outside the window, then let go of the mouse button {should stop dragging}
- Right click on the circle {should not drag, but bring up the context menu}
- Right button drag the circle {should not drag, but bring up the context menu on Mac or Linux, or do nothing on Windows}

- Drag with the middle button {should not drag, but enable autoscroll}
- Drag with the left button, then hold down right button, continue drag, then release left button, then move mouse, then release right button {should stop dragging when releasing left button; I want a different behavior from [[http://wpt.live/pointerevents/pointerevent_pointercapture-not-lost-in-chorded-buttons.html][this test]]}
- Chords¹: drag with the left button, then hold down Ctrl, then release the left button {Mac/Firefox behaves differently, giving =pointerdown.left= and then =pointerup.right= whereas other browsers give =pointerdown.left= and =pointerup.left=}
- While dragging, Alt+Tab (Cmd+Tab) to switch windows, then let go of the mouse button {should stop dragging}
- While dragging, use keyboard to scroll {should still be dragging²}
- While dragging, use scrollwheel to scroll {should still be dragging²}
- While dragging, use middle button to scroll {should still be dragging²}
- While dragging, resize the window {should still be dragging²}
- Select all text on page, then drag the circle {should drag the circle, not the text}
- Plug in two mice, start dragging on one, click on the other {want this to continue dragging, but it won't³}
- On Mac, use an iPad as a second screen, drag with stylus on a mac browser {should drag}
- While dragging, put the computer to sleep and then wake it up and continue the drag {??}
- While dragging, unplug the mouse and plug it back in {??}

Things to try with touch:

- Drag the circle up or down {should not scroll the page}
- Drag the diagram up or down {should scroll the page}
- Long press on the circle {should not select the text or bring up a menu}
- Use two separate fingers to drag two separate objects {should both drag independently}

- Use two separate fingers to drag one object {should only drag with the first finger⁴}
- Drag with one finger then try to pinch zoom with a second finger {should not zoom}
- Drag with one finger then try to pinch zoom with two other fingers {does not zoom, not sure what it should do}
- Drag with one finger then rotate the phone {will rotate and continue dragging on iOS; will not rotate on Android}
- On iPad, use Mac "continuity" to drag with the mouse on an ipad browser {should drag}

Notes:

- ¹solution [[http://wpt.live/pointerevents/pointerevent_pointermove_on_chorded_mouse_button.html][based on pointermove getting called for button changes]]
- ²it won't update until you nudge the mouse pointer
- ³this is a limitation of the OS level mouse handling
- ⁴I have a solution but haven't implemented or tested it


* Test: SVG single element
:PROPERTIES:
:CUSTOM_ID: test-2a-svg-single-element
:END:

#+begin_export html
<figure class="w-full">
  <svg viewBox="-330 -50 660 100">
    <rect x="-330" y="-50" width="100%" height="100%" fill="url(#pattern-dots)" />
    <circle class="draggable" stroke="black" stroke-width="0.5" r="30" />
  </svg>
  <figcaption>Draggable circle</figcaption>
  <button>Reset</button>
</figure>
#+end_export

- Basic tests work
- On desktop, scrolling while dragging doesn't drag until you move your mouse a tiny amount. This could be solved either with a timer or by catching the scroll event. Low priority for me.

* Test: SVG nested element with text
:PROPERTIES:
:CUSTOM_ID: test-2b-svg-nested-element-with-text
:END:

#+begin_export html
<figure class="w-full">
  <svg viewBox="-330 -50 660 100">
    <rect x="-330" y="-50" width="100%" height="100%" fill="url(#pattern-dots)" />
    <g class="draggable">
      <circle stroke="black" stroke-width="0.5" r="30" />
      <g font-size="16" text-anchor="middle" fill="white">
        <text dy="0.0em">Drag</text>
        <text dy="1.0em">me</text>
      </g>
    </g>
  </svg>
  <figcaption>Draggable circle + text</figcaption>
  <button>Reset</button>
</figure>
#+end_export

- I use pointer capture on =currentTarget= not =target=. 
- While dragging, I set CSS ~user-select: none~. This prevents selecting the text by dragging or double clicking (desktop) or long press (mobile). But I don't want this /all/ the time. When not dragging, I want the text to be selectable.
- On desktop, if you select the text of the page and then try to drag it, it will let you drag that text outside the browser. But if you also try to drag this circle the two drag handlers will intefere. Use ~preventDefault()~ on the =dragstart= event to fix this.

* Test: Canvas drawing
:PROPERTIES:
:CUSTOM_ID: test-2c-canvas-drag-to-draw
:END:

The same drag event handlers can be used for drawing instead of moving an object:

#+begin_export html
<figure class="w-full">
  <canvas width="660" height="100" style="cursor:crosshair"/>
  <figcaption>Drag to draw on the canvas</figcaption>
</figure>
#+end_export

* Test: Canvas dragging
:PROPERTIES:
:CUSTOM_ID: test-2d-canvas-drag-a-handle
:END:

#+begin_export html
<figure class="w-full">
  <canvas width="1000" height="150" />
  <figcaption>Drag the circle to move it</figcaption>
  <button>Reset</button>
</figure>
#+end_export

- ⁴if I put a second finger on the diagram it jumps to the second finger's position. This is because the /same/ is getting the =pointermove= event for the second finger, whereas in the other demos a /different/ element gets the events for the second finger. To fix this, I need to use the =.pointerId= field to make sure the =pointermove= event I got is for the same finger that started the drag.

* Test: HTML div absolute positioned
:PROPERTIES:
:CUSTOM_ID: test-2e-html-div-absolute-positioned
:END:

#+begin_export html
<figure class="w-full">
  <div class="diagram" style="position:relative;width:100%;height:100px">
    <div class="draggable" style="position:absolute;width:5em;height:1.5em">Drag me</div>
  </div>
  <figcaption>Drag the box to move it</figcaption>
  <button>Reset</button>
</figure>
#+end_export

- It is possible to place the box outside the container by placing it on the right, then shrinking the browser size. I'm going to leave this up to the application and not try to solve it generically.

* Test: HTML div css transform
:PROPERTIES:
:CUSTOM_ID: test-2f-html-div-css-transform
:END:

#+begin_export html
<figure class="w-full">
  <div class="diagram" style="position:relative;width:100%;height:100px">
    <div class="draggable" style="transform:translate(0px,0px);width:5em;height:1.5em">Drag me</div>
  </div>
  <figcaption>Drag the box to move it</figcaption>
  <button>Reset</button>
</figure>
#+end_export

* Notes
:PROPERTIES:
:CUSTOM_ID: notes
:END:

/None/ of these handle CSS transforms on the parent elements. This is an unsolved issue, not only for me, but also other libraries like d3.js. See https://github.com/d3/d3-selection/issues/67  and https://bugzilla.mozilla.org/show_bug.cgi?id=1610093 . There's probably /something/ we can do using =window.getComputedStyle(element)= but this is a low priority for me, as I almost never use css transforms above a draggable element.

#+begin_export html
<style>
  svg, canvas, div.diagram { background: #eee; box-shadow: 0 1px 3px 1px rgba(0,0,0,0.3); width: 100%; }

  .draggable { cursor: grab; }
  .dragging { cursor: grabbing; user-select: none; }

  circle.draggable, .draggable circle { fill: hsl(0 50% 50%); }
  circle.draggable.dragging, .dragging circle { fill: hsl(200 50% 50%); }
  div.draggable { background: hsl(0 50% 50%); color: white; }
  div.draggable.dragging { background: hsl(200 50% 50%); }

  circle.captured, .captured circle { stroke: hsl(200 100% 70%); stroke-width: 2px; }
  div.captured { border: 2px solid hsl(200 100% 70%); }

</style>

<x:footer>
  <svg width="0" height="0">
    <defs>
      <pattern id="pattern-dots" width="10" height="10" patternUnits="userSpaceOnUse">
        <circle cx="5" cy="5" fill="hsl(0 10% 80%)" r="1" />
      </pattern>
    </defs>
  </svg>
  <script src="tests.js"></script>
</x:footer>
#+end_export
